language: rust
script: cargo test --all --all-features $CARGOFLAGS

jobs:
  include:
  - rust: 1.17.0
  - rust: stable
  - rust: beta
  - rust: nightly
  - rust: nightly
    env: CARGOFLAGS=--target=wasm32-unknown-unknown
    install: rustup target add wasm32-unknown-unknown

notifications:
  webhooks: http://build.servo.org:54856/travis
