[package]

name = "url"
version = "0.1.1"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "URL parser for Rust"
documentation = "http://servo.github.io/rust-url/url/index.html"
repository = "https://github.com/servo/rust-url"
readme = "README.md"
keywords = ["url", "parser"]
license = "MIT/Apache-2.0"


[dependencies]
encoding = "0.2"
