[package]

name = "url"
version = "0.2.3"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

[features]

query_encoding = ["encoding"]

[dependencies.encoding]

git = "https://github.com/lifthrasiir/rust-encoding"
optional = true
