[package]

name = "url"
version = "0.1.0"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

[[lib]]

name = "url_"
path = "src/url.rs"

[dependencies.encoding]

git = "https://github.com/lifthrasiir/rust-encoding"
